# Generated by Django 4.1.6 on 2023-02-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Purschase',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
