# Generated by Django 4.1.6 on 2023-02-14 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplies', '0004_customer_sex_alter_purschase_dop'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappedCoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_coupons', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='purschase',
            name='dop',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 21, 39, 55, 253750)),
        ),
    ]
