# Generated by Django 4.1.6 on 2023-02-15 06:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supplies', '0005_mappedcoupons_alter_purschase_dop'),
    ]

    operations = [
        migrations.AddField(
            model_name='purschase',
            name='purchase_customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Supplies.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purschase',
            name='dop',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 12, 1, 50, 581600)),
        ),
    ]
