# Generated by Django 4.1.6 on 2023-02-23 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplies', '0012_alter_purschase_dop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purschase',
            name='dop',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 14, 43, 33, 915960)),
        ),
    ]
