# Generated by Django 4.1.6 on 2023-02-23 09:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supplies', '0013_alter_purschase_dop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.CharField(max_length=10, unique=True)),
                ('dop', models.DateTimeField(default=datetime.datetime(2023, 2, 23, 14, 45, 39, 222023))),
                ('total_purchase', models.BigIntegerField(default=0)),
                ('availed_coupons', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('coupons', models.JSONField()),
                ('purchase_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='Supplies.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='Purschase',
        ),
    ]
