# Generated by Django 4.1.6 on 2023-02-25 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplies', '0016_alter_purchase_dop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='dop',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 20, 17, 53, 644661)),
        ),
    ]
