# Generated by Django 4.1.6 on 2023-03-22 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplies', '0019_sales_delete_mappedcoupons_alter_purchase_dop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='active',
        ),
        migrations.AddField(
            model_name='purchase',
            name='expired_coupons',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='dop',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 12, 13, 46, 844565)),
        ),
    ]
